l_english:
  SETTING_AUTOSAVE_TO_CLOUD: "Autosave to cloud"
  SETTING_SAVE_FILE_FORMAT: "Default save format"
  SETTING_SAVE_FILE_FORMAT_TOOLTIP: "This option is overridden in Ironman, Cloud, and Debug mode"
  OPTION_SAVE_FILE_TEXT: "Text"
  OPTION_SAVE_FILE_ZIP_TEXT_ALL: "Zipped text"
  OPTION_SAVE_FILE_ZIP_BINARY_ALL: "Zipped binary"
  SETTING_TOOLTIP_MODE: "Tooltip Mode"
  SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nChoose how the tooltips should lock:\n   #b Mouse Tendency#! - Locks it if you move the mouse towards the tooltip.\n   #b Timer Lock#! - Locks it after a set time.\n   #b Action Lock#! - Locks it with middle mouse button."
  SETTING_TOOLTIP_MODE_NO_LOCK: "No lock"
  SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Mouse Tendency"
  SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "Action Lock ( Mouse Anchor )"
  SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "Timer Lock ( Mouse Anchor )"
  SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "Action Lock"
  SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "Timer Lock"
  SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nSets the delay before the tooltip shows up when hovering an element with a tooltip."
  SETTING_TOOLTIP_DELAY: "Show Delay"
  SETTING_TOOLTIP_UNLOCK_TIME: "Unlock Delay"
  SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nSets the delay before tooltips are unlocked."
  SETTING_TOOLTIP_LOCK_TIME: "Lock Delay"
  SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nSets the delay before tooltips are locked."
  SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Locked Open Delay"
  SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nSets the delay before tooltips are locked when another tooltip is already open."
  SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Advanced"
  SETTINGS_CATEGORY_AUDIO_GENERAL: "General"
  SETTINGS_CATEGORY_SFX: "Sound Effects"
  SETTINGS_CATEGORY_MFX: "Music"
  SETTINGS_CATEGORY_LANGUAGE: "Language"
  SETTINGS_CATEGORY_SAVE_GAMES: "Save Games"
  SETTINGS_CATEGORY_TOOLTIPS: "Tooltip Settings"
  SETTINGS_CATEGORY_MAP_CONTROLS: "Map Controls"
  SETTINGS_CATEGORY_MAPMODES: "Map Modes"
  SETTING_SHADER_QUALITY: "Shader Quality"
  SETTING_SHADER_QUALITY_TOOLTIP: "#T Shader Quality\n#!Determines the quality of various shaders and effects.\n\n#T High:#! Improves quality of some shader effects at the cost of performance.\n\n#T Medium:#! Default setting for the intended graphical experience.\n\n#T Low:#! This setting is made for low-end machines and is not recommended due to the loss in visual quality. Multiple shaders are simplified to push graphical performance."
  SETTING_SHOW_NUDITY: "Show nudity"
  SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nSets whether characters can be shown nude."
  SETTINGS_CATEGORY_GAME_PORTRAITS: "Portraits"
  SETTING_SOUNDTRACK: "Background Music"
  SETTING_SOUNDTRACK_TOOLTIP: "General background music"
  SETTING_MUSIC_STINGERS: "Music Stingers"
  SETTING_MUSIC_STINGERS_TOOLTIP: "Short musical phrases to enhance gameplay"
  # Audio - These are copies of clausewitz keys due to case sensitivity
  SETTING_MUSIC: "Music"
  SETTING_AMBIENT: "Ambient"
  SETTING_MUSIC_TOOLTIP: "#T Music Volume\n#!Sets the volume of the music."
  SETTING_AMBIENT_TOOLTIP: "#T Ambient Volume\n#!Sets the volume of environmental ambience."

  SETTING_MAP_TOOLTIP_DELAY: "Map Tooltip Delay"
  SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nSets the delay before the map tooltip is shown."

  SETTING_MAP_MODE_DELAY: "Mapmode Delay"
  SETTING_MAP_MODE_DELAY_TOOLTIP: "Delay before switching to a new Mapmode, in seconds"
  SETTING_MAP_MODE_FADE_IN: "Mapmode Fade-in"
  SETTING_MAP_MODE_FADE_IN_TOOLTIP: "Time for a new Mapmode to fade-in after the old has faded out, in seconds"
  SETTING_MAP_MODE_FADE_OUT: "Mapmode Fade-out"
  SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "Time for the current Mapmode to fade-out after the Mapmode Delay when a new Mapmode is to be applied, in seconds"

  color_blind_mode_test: "Test"
